name: Python PytestArch Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.14'

    - name: Install dependencies and pytestarch
      run: |
        pip install -r requirements.txt
        pip install pytestarch

    - name: Perform architecture testing with pytestarch
      run: |
        pytest --architecture