name: Check dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.15'

    - name: Install Safety
      run: |
        python -m pip install safety

    - name: Check dependencies
      run: |
        safety check --full-report
