name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # replace '3.x' with the Python version you are using

    - name: Install Snyk CLI
      run: |
        curl https://snyk.io/install | sh
        sudo mv snyk /usr/local/bin/

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Test with Snyk
      run: snyk test --severity-threshold=high
